# Generated by Django 5.1.4 on 2024-12-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Detection_platform', '0009_rename_buyer_user_remove_game_buyer_delete_new_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
