# Generated by Django 5.1.3 on 2024-12-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_game_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='password',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='age_limited',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='game',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=99),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(default='Very good game, bro!'),
        ),
    ]
