# Generated by Django 5.1.3 on 2024-12-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0003_buyer_password_alter_game_age_limited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=99),
        ),
    ]
