# Generated by Django 5.1.3 on 2024-12-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0007_alter_game_age_limited'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'New_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Things',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'things',
                'managed': False,
            },
        ),
    ]
