# Generated by Django 5.1.4 on 2024-12-09 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0008_new_table_things'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buyer',
            new_name='User',
        ),
        migrations.RemoveField(
            model_name='game',
            name='buyer',
        ),
        migrations.DeleteModel(
            name='New_table',
        ),
        migrations.DeleteModel(
            name='Things',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
