# Generated by Django 5.1.4 on 2024-12-12 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0013_detectedobject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
